# Generated by Django 4.1.1 on 2022-09-05 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=60, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=60, verbose_name="Last Name"),
                ),
                ("email", models.EmailField(max_length=100, verbose_name="Email")),
                ("password", models.CharField(max_length=120, verbose_name="Password")),
            ],
        ),
        migrations.CreateModel(
            name="UserLoginTokens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(max_length=400, verbose_name="Access Token"),
                ),
                (
                    "refresh_token",
                    models.CharField(max_length=400, verbose_name="Refresh Token"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="mapapp.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_line",
                    models.CharField(
                        default=None, max_length=400, verbose_name="First Line"
                    ),
                ),
                (
                    "second_line",
                    models.CharField(
                        default=True, max_length=400, verbose_name="Second Line"
                    ),
                ),
                (
                    "town_city",
                    models.CharField(
                        default=True, max_length=100, verbose_name="Town/City"
                    ),
                ),
                (
                    "postcode",
                    models.CharField(
                        default=True, max_length=50, verbose_name="Postcode"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="mapapp.user"
                    ),
                ),
            ],
        ),
    ]
