# Generated by Django 4.1.1 on 2022-09-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapapp", "0003_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.SmallIntegerField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
