# Generated by Django 4.1.1 on 2022-09-21 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mapapp", "0004_alter_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSavedAddresses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.IntegerField(default=None, verbose_name="Latitude")),
                ("lng", models.IntegerField(default=None, verbose_name="Longitude")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="mapapp.user"
                    ),
                ),
            ],
        ),
    ]
