# Generated by Django 4.1.1 on 2022-09-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapapp", "0006_alter_usersavedaddresses_lat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersavedaddresses",
            name="lat",
            field=models.CharField(
                default=None, max_length=50, verbose_name="Latitude"
            ),
        ),
        migrations.AlterField(
            model_name="usersavedaddresses",
            name="lng",
            field=models.CharField(
                default=None, max_length=50, verbose_name="Longitude"
            ),
        ),
    ]
