# Generated by Django 4.1.1 on 2022-10-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapapp", "0009_usersavedaddresses_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
